config/routes.rb
Rails.application.routes.draw do

  root to: "people#index"

  post :add_note, to: "application#add_note"

  devise_for :users

  resources :users, only: :index
  get 'unauthorized', to:  'users#unauthorized', as: :unauthorized

  resources :groups

  resources :images do
    member do
      get 'full_size', to: 'images#full_size'
      get 'remove_linked_event', to: 'images#remove_linked_event'
      get 'remove_linked_person', to: 'images#remove_linked_person'
      get 'remove_linked_group', to: 'images#remove_linked_group'
    end
  end

  resources :people do
    member do
      get 'remove_linked_image', to: 'people#remove_linked_image'
      get 'remove_linked_group', to: 'people#remove_linked_group'
      get 'remove_linked_event', to: 'people#remove_linked_event'
    end
    collection do
      get 'search', to: "people#search"
    end
  end

  resources :events do
    member do
      get 'remove_linked_image', to: 'events#remove_linked_image'
      get 'remove_linked_group', to: 'events#remove_linked_group'
      get 'remove_linked_event', to: 'events#remove_linked_event'
      get 'remove_linked_person', to: 'events#remove_linked_person'
    end
  end


# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/models/person.rb
class Person < ApplicationRecord

  has_many :person_events
  has_many :events, through: :person_events
  has_many :person_images
  has_many :images, through: :person_images
  has_many :group_people
  has_many :groups, through: :group_people
  has_many :note_people
  has_many :notes, through: :note_people

  def full_name
    first_name.to_s + " " + last_name.to_s
  end

end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: [:show, :edit, :update, :destroy]

  # GET /people
  # GET /people.json
  def index
    @people = Person.all.order(last_name: :asc).page(params[:page])
  end

  # GET /people/1
  # GET /people/1.json
  def show
    @photo_arr = @person.images.each_slice(4).to_a
  end

  # GET /people/new
  def new
    @person = Person.new
    @groups_for_select = Group.all.order(name: :asc).map{ |group| [group.name, group.id] }
    @events_for_select = Event.all.order(name: :asc).map{ |event| [event.name, event.id] }
  end

  # GET /people/1/edit
  def edit
    @events_for_select = Event.all.order(name: :asc).map{ |event| [event.name, event.id] }
    @groups_for_select = Group.all.order(name: :asc).map{ |group| [group.name, group.id] }
  end

  # POST /people
  # POST /people.json
  def create
    @person = Person.new(person_params)

    respond_to do |format|
      if @person.save
        process_linking_params
        format.html { redirect_to @person, notice: 'Person was successfully created.' }
        format.json { render :show, status: :created, location: @person }
      else
        format.html { render :new }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1
  # PATCH/PUT /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        process_linking_params
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
        format.json { render :show, status: :ok, location: @person }
      else
        format.html { render :edit }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @person.destroy
    respond_to do |format|
      format.html { redirect_to people_url, notice: 'Person was successfully deleted' }
      format.json { head :no_content }
    end
  end

  def remove_linked_image
    @person = Person.find(params[:id])
    photo = Image.find(params[:photo_id])
    if @person.images.delete(photo)
      redirect_to @person, notice: "Linked image successfully removed"
    else
      redirect_to @person, notice: "Could not remove linked image"
    end
  end

  def remove_linked_group
    @person = Person.find(params[:id])
    group = Group.find(params[:group_id])
    if @person.groups.delete(group)
      redirect_to @person, notice: "Linked group successfully removed"
    else
      redirect_to @person, notice: "Could not remove linked group"
    end
  end

  def remove_linked_event
    event = Event.find(params[:event_id])
    if @person.events.delete(event)
      redirect_to @person, notice: "Linked event successfully removed"
    else
      redirect_to @person, notice: "Could not remove linked event"
    end
  end

  def search
    search_params = params[:search_params].downcase
    if search_params.split.length == 1
      @people = Person.where("lower(first_name) LIKE :search", search: "%#{search_params}%").or(
                            Person.where("lower(last_name) LIKE :search", search: "%#{search_params}%"))
    else
      first_name = "%#{search_params.split.first}%"
      last_name = "%#{search_params.split.last}%"
      @people = Person.where("lower(first_name) LIKE :first_name AND lower(last_name) LIKE :last_name", last_name: last_name, first_name: first_name).or(
                Person.where("lower(last_name) LIKE :first_name AND lower(first_name) LIKE :last_name", last_name: last_name, first_name: first_name))

    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:id])
    end

    def process_linking_params
        if params[:person_images].present?
          params[:person_images].each do |img|
            image = Image.new(description: img.original_filename, image: img.tempfile)
            if image.save
              @person.images << image
            end
          end
        end
        if params[:person][:link_group].present?
          group = Group.find(params[:person][:link_group])
          @person.groups << group
        end
        if params[:person][:link_event].present?
          event = Event.find(params[:person][:link_event])
          @person.events << event
        end
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def person_params
      params.require(:person).permit(:first_name, :last_name, :location)
    end
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/people/_form.html.erb
<%= form_with(model: person, local: true) do |form| %>
  <% if person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
        <% person.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="row">
    <div class="six columns">
      <%= form.label :first_name %>  
      <%= form.text_field :first_name, class: "u-full-width" %>
    </div>
    
    <div class="six columns">
     <%= form.label :last_name %>
      <%= form.text_field :last_name, class: "u-full-width" %>
    </div>
  </div>
  
  <div class="row">
    <div class="twelve columns">
      <%= form.label :location %>
      <%= form.text_field :location, class: "u-full-width" %>
    </div>
  </div>
<div class="row">
  <div class="six columns">
    <h4>Groups</h4>
    <%= form.label :link_group %>
    <%= form.select :link_group, @groups_for_select, include_blank: "add this person to a group", class: "u-full-width"%>
    <% if @person.groups.any? %>
      <% @person.groups.each do |group| %>
        <li><%= group.name %></li>
      <% end %>
    <% end %>
  </div>
  <div class="six columns">
    <h4>Events</h4>
    <%= form.label :link_event %>
    <%= form.select :link_event, @events_for_select, include_blank: "add events", class: "u-full-width" %>
    <% if @person.events.any? %>
       <ul>
        <% @person.events.each do |event| %>
          <li><%= event.name %></li>
        <% end %>
      </ul>
    <% end %>
  </div>
</div>

  <div class="row">
    <div class="twelve columns">
      <%= form.label :images %>
      <%= form.file_field :images, multiple: true, name: "person_images[]", class: "u-full-width"%>
    </div>



    <div class="actions">
      <%= form.submit class: "button button-primary" %>
  </div>
<% end %>

app/views/people/edit.html.erb
<h1>Editing Person</h1>

<%= render 'form', person: @person %>

<%= link_to 'Show', @person %> |
<%= link_to 'Back', people_path %>

app/views/people/index.html.erb
<h1>People</h1>
<div class="row">
  <div class="six columns">
    <%= form_tag search_people_path, method: :get do %>
      <div>Search by first name, last name, or first and last names</div> 
      <%= search_field_tag :search_params, nil, class: "u-full-width" %>
      <%= submit_tag "Search" %>
    <% end %>
  </div>
</div>

<div class="row">
  <%= link_to 'New Person', new_person_path %>
</div>
<div class="row"
  <%= paginate @people %>
</div>
<table>
  <thead>
    <tr>
      <th></th>
      <th>Name</th>
      <th>Groups</th>
      <th>Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @people.each do |person| %>
      <tr>
        <td>
          <% if person.images.any? %>
            <%= link_to person do %>
              <%= image_tag person.images.first.image.thumb.url %>
            <% end %>
          <% end %>
        </td>
        <td><%= link_to person.full_name, person %></td>
        <td><% person.groups.each do |group| %>
              <%= link_to group.name + " ", group %>
            <% end %>
            </td>
        <td><%= link_to 'Edit', edit_person_path(person) %> | <%= link_to 'Delete', person, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/people/new.html.erb
<h1>New Person</h1>

<%= render 'form', person: @person %>

<%= link_to 'Back', people_path %>

app/views/people/search.html.erb
<h2>Search Results</h2>
<div>search params: <strong><%= params[:search_params] %></strong></div>

<table>
  <thead>
    <tr>
      <th></th>
      <th>Name</th>
      <th>Location</th>
      <th>Groups</th>
    </tr>
  </thead>
  <tbody> 
    <% @people.each do |person| %>
      <tr>
        <td><%= link_to person do %>
            <%= image_tag person.images.first.image.thumb.url if person.images.any? %>
            <% end %></td>
        <td><%= link_to person.full_name, person %></td>
        <td><%= person.location %></td>
        <td><%= person.groups.pluck(:name).join(", ") %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/people/show.html.erb
<h4>
  <%= @person.full_name %>
</h4>
<div>
  <%= link_to 'Edit', edit_person_path(@person) %> 
</div>
<div>
  <%= @person.location %>
</div>
<div>
  <% if @person.events.any? %>
    <h4>Events</h4>
    <ul>
      <% @person.events.each do |event| %>
        <li>
          <%= link_to event.name, event %>
          <%= link_to remove_linked_event_person_path(event_id: event.id), data: {confirm: "remove linked event?"} do %>
            <%= fa_icon "times-circle" %>
          <% end %>
        </li>
      <% end %>
    </ul>
  <% end %>
</div>
<div>
  <% if @person.groups.any? %>
    <h4>Groups</h4>
    <ul>
      <% @person.groups.each do |group| %>
        <li><%= link_to group.name, group %>
        <%= link_to remove_linked_group_person_path(group_id: group.id), data: {confirm: "remove linked group?"}  do %>
          <%= fa_icon "times-circle" %>
      <% end %></li>
      <% end %>
    </ul>
  <% end %>
</div>
<div>
  <% if @person.notes.any? %>
    <h4>Notes</h4>
    <% @person.notes.each do |note| %>
      <div><%= note.content %></div>
      <div><%= "Added #{note.created_at}" %></div>
    <% end %>
  <% end %>
</div>

<div class="note-form row">
  <%= render partial: "layouts/note_form", locals: { item_type: :person, item_id: @person.id } %>
</div>
<div class="photo-container">
  <% @photo_arr.each do |row| %>
    <div class="row">
      <% row.each do |image| %>
        <div class="three columns">
          <%= link_to remove_linked_image_person_path(photo_id: image.id), data: {confirm: "remove linked image?"} do %>
            <%= fa_icon "times-circle", class: "pull-right" %>
          <% end %>
          <%= link_to image_path(image) do %>
            <%= image_tag image.image.thumb.url %>
          <% end %>
        </div>
      <% end %>
    </div>
  <% end %>
</div>