config/routes.rb
Rails.application.routes.draw do

  root to: "people#index"

  post :add_note, to: "application#add_note"

  devise_for :users

  resources :users, only: :index
  get 'unauthorized', to:  'users#unauthorized', as: :unauthorized

  resources :groups

  resources :images do
    member do
      get 'full_size', to: 'images#full_size'
      get 'remove_linked_event', to: 'images#remove_linked_event'
      get 'remove_linked_person', to: 'images#remove_linked_person'
      get 'remove_linked_group', to: 'images#remove_linked_group'
    end
  end

  resources :people do
    member do
      get 'remove_linked_image', to: 'people#remove_linked_image'
      get 'remove_linked_group', to: 'people#remove_linked_group'
      get 'remove_linked_event', to: 'people#remove_linked_event'
    end
    collection do
      get 'search', to: "people#search"
    end
  end

  resources :events do
    member do
      get 'remove_linked_image', to: 'events#remove_linked_image'
      get 'remove_linked_group', to: 'events#remove_linked_group'
      get 'remove_linked_event', to: 'events#remove_linked_event'
      get 'remove_linked_person', to: 'events#remove_linked_person'
    end
  end


# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord

  has_many :event_videos
  has_many :videos, through: :event_videos
  has_many :person_events
  has_many :people, through: :person_events
  has_many :event_images
  has_many :images, through: :event_images
  has_many :note_events
  has_many :notes, through: :note_events

  accepts_nested_attributes_for :images
end

app/models/event_image.rb
class EventImage < ApplicationRecord

  belongs_to :event
  belongs_to :image

end

app/models/event_video.rb
class EventVideo < ApplicationRecord

  belongs_to :event
  belongs_to :video

end

app/models/group.rb
class Group < ApplicationRecord

  has_many :group_people
  has_many :people, through: :group_people
  has_many :group_images
  has_many :images, through: :group_images
  has_many :note_groups
  has_many :notes, through: :note_groups
end

app/models/group_image.rb
class GroupImage < ApplicationRecord

  belongs_to :group
  belongs_to :image

end

app/models/group_person.rb
class GroupPerson < ApplicationRecord

  belongs_to :group
  belongs_to :person
end

app/models/image.rb
class Image < ApplicationRecord

  mount_uploader :image, ImageUploader

  has_many :person_images
  has_many :people, through: :person_images
  has_one :event_image
  has_one :event, through: :event_image
  has_many :group_images
  has_many :groups, through: :group_images
  has_many :note_images
  has_many :notes, through: :note_images

end

app/models/note.rb
class Note < ApplicationRecord

  belongs_to :note_event, optional: true
  belongs_to :note_group, optional: true
  belongs_to :note_image, optional: true
  belongs_to :note_person, optional: true

end

app/models/note_event.rb
class NoteEvent < ApplicationRecord

  belongs_to :event
  belongs_to :note

end

app/models/note_group.rb
class NoteGroup < ApplicationRecord

  belongs_to :note
  belongs_to :group

end

app/models/note_image.rb
class NoteImage < ApplicationRecord

  belongs_to :note
  belongs_to :image

end

app/models/note_person.rb
class NotePerson < ApplicationRecord

  belongs_to :note
  belongs_to :person

end

app/models/person.rb
class Person < ApplicationRecord

  has_many :person_events
  has_many :events, through: :person_events
  has_many :person_images
  has_many :images, through: :person_images
  has_many :group_people
  has_many :groups, through: :group_people
  has_many :note_people
  has_many :notes, through: :note_people

  def full_name
    first_name.to_s + " " + last_name.to_s
  end

end

app/models/person_event.rb
class PersonEvent < ApplicationRecord

  belongs_to :person
  belongs_to :event

end

app/models/person_image.rb
class PersonImage < ApplicationRecord

  belongs_to :person
  belongs_to :image

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :rememberable, :recoverable, :trackable, :validatable, :timeoutable #add :invitable :lockable,
end

app/models/video.rb
class Video< ApplicationRecord

  mount_uploader :video, VideoUploader

  has_one :event_image
  has_one :event, through: :event_image

end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  def index
    @events = Event.all.order(date: :asc).page(params[:page])
  end

  def show
    @event = Event.find(params[:id])
    @photo_arr = @event.images.each_slice(4).to_a
    @video_arr = @event.videos.to_a
end

  def new
    @event = Event.new
    @people_for_select = Person.all.map{ |person| ["#{person.first_name} #{person.last_name}", person.id] }
  end

  def create
    @event = Event.new(event_params)
    respond_to do |format|
      if @event.save
        process_linking_params
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
    @event = Event.find(params[:id])
    @people_for_select = Person.all.map{ |person| ["#{person.first_name} #{person.last_name}", person.id] }
  end

  def update
    @event = Event.find(params[:id])
    respond_to do |format|
      if @event.update(event_params)
      process_linking_params
        # @event.people << Person.find(params[:image][:link_person])
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /images/1
  # DELETE /images/1.json
  def destroy
    @event = Event.find(params[:id])
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  def remove_linked_group
    @event = Event.find(params[:id])
    group = Group.find(params[:group_id])
    if @evnet.groups.delete(group)
      redirect_to @event, notice: "Linked group successfully removed"
    else
      redirect_to @event, notice: "Could not remove linked group"
    end
  end


  def remove_linked_person
    @event = Event.find(params[:id])
    person = Person.find(params[:person_id])
    if @event.people.delete(person)
      redirect_to @event, notice: "Linked person successfully removed"
    else
      redirect_to @event, notice: "Could not remove linked_person"
    end
  end

  def remove_linked_image
    @event = Event.find(params[:id])
    photo = Image.find(params[:photo_id])
    if @event.images.delete(photo)
      redirect_to @event, notice: "Linked image successfully removed"
    else
      redirect_to @event, notice: "Could not remove linked image"
    end
  end

  private

    def event_params
      params.require(:event).permit(:name, :description, :date, :location )
    end

    def process_linking_params
        if params[:event_images].present?
          params[:event_images].each do |img|
            image = Image.new(description: img.original_filename, image: img.tempfile)
            if image.save
              @event.images << image
            end
          end
        end
        if params[:event_videos].present?
          params[:event_videos].each do |video|
            video = Video.new(description: video.original_filename, video: video.tempfile)
            if video.save
              @event.videos << video
            end
          end
        end
        if params[:event_people].present?
          params[:event_people].each do |person|
            unless person.blank?
              person = Person.find(person)
              @event.people << person unless @event.people.include?(person)
            end
          end
        end

        #if params[:event][:link_group].present?
       #   group = Group.find(params[:person][:link_group])
       #   @person.groups << group
       # end
       # if params[:person][:link_event].present?
       #   event = Event.find(params[:person][:link_event])
       #   @person.events << event
       # end
    end

end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/events/edit.html.erb
<h1>Edit Event</h1>

<%= form_with(model: @event, local: true) do |form| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this image from being saved:</h2>

      <ul>
        <% @event.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="twelve columns">
      <%= form.label :name %>
      <%= form.text_field :name, class: "u-full-width" %>
    </div>
  </div>

  <div class="row">
    <div class="twelve columns">
      <%= form.label :description %>
      <%= form.text_area :description, class: "u-full-width" %>
    </div>
  </div>
  <div class="row">
    <div class="six columns">
      <%= form.label :date %>
      <%= form.date_field :date, class: "u-full-width" %>
    </div>
    <div class="six columns">
      <%= form.label :location %>
      <%= form.text_field :location, class: "u-full-width" %>
    </div>
  </div>

  <div class="row">
    <div class="twelve columns select-container">
      <%= form.label :people %><small>use ctrl or shift to select multiple</small>
      <%= form.select :people, options_for_select(@people_for_select, @event.people), {include_blank: true}, { name: 'event_people[]', class:"u-full-width multiple-select", multiple: true} %> 
    </div>
  </div>

  <div class="row">
    <%= form.label :images %>
    <%= form.file_field :images, multiple: true, name: "event_images[]", class: "u-full-width" %>
  </div>

  <div class="field">
    <%= form.label :videos %>
    <%= form.file_field :videos, multiple: true, name: "event_videos[]" %>
  </div>


  <div class="actions">
    <%= form.submit class: "button button-primary" %>
  </div>
<% end %>

<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<h1>Events</h1>
<%= link_to 'New Event', new_event_path %>
<%= paginate @events %>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Date</th>
      <th>Description</th>
      <th>Images</th>
      <th>Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= link_to event.name, event %></td>
        <td><%= link_to event.date, event %></td>
        <td><%= link_to event.description, event %></td>
        <td><% if event.images.any? %>
              <%= link_to event do %>
                <%= image_tag event.images.first.image.thumb.url %>
              <% end %>
            <% end %>
        </td>
        <td><%= link_to 'Edit', edit_event_path(event) %> | <%= link_to 'Delete', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= form_with(model: @event, local: true) do |form| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this image from being saved:</h2>

      <ul>
        <% @event.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :date %>
    <%= form.date_field :date %>
  </div>
  <div class="row">
    <div class="twelve columns select-container">
      <%= form.label :people %>
      <%= form.select :people, options_for_select(@people_for_select), { include_blank: true}, {class: "u-full-width multiple-select", name: "event_people[]", multiple: true} %> 
    </div>
  </div>
  <div class="field">
    <%= form.label :images %>
    <%= form.file_field :images, multiple: true, name: "event_images[]" %>
  </div>
  
  <div class="field">
    <%= form.label :videos %>
    <%= form.file_field :videos, multiple: true, name: "event_videos[]" %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<h4><%= @event.name %></h4>
<%= link_to "Edit", edit_event_path(@event) %>
<div>
  <%= @event.date %>, <%= @event.location %>
</div>
<div>
  <%= @event.description %>
</div>
<div>
  <h4>Participants</h4>
  <ul>
    <% @event.people.each do |person| %>
      <li>
        <%= link_to "#{person.full_name}, #{person.location}", person %>
        <%= link_to remove_linked_person_event_path(person_id: person.id), data: { confirm: "remove linked person?" } do %>
          <%= fa_icon "times-circle", class: "pull-right" %>
        <% end %>
      </li>
    <% end %>
  </ul>
</div>
<div>
  <% if @event.notes.any? %>
    <h4>Notes</h4>
    <% @event.notes.each do |note| %>
      <div><%= note.content %></div>
      <div><%= "Added #{note.created_at}" %></div>
    <% end %>
  <% end %>
</div>

<div class="note-form row">
  <%= render partial: "layouts/note_form", locals: { item_type: :event, item_id: @event.id } %>
</div>

<div class="video-container">
  <% @video_arr.each do |video| %>
    <div>
      <%= video_tag video.video.to_s,  controls: true, size: "900x900" %>
    </div>
  <% end %>
<div>

<div class="photo-container">
  <% @photo_arr.each do |row| %>
    <div class="row">
      <% row.each do |image| %>
        <div class="three columns">
          <%= link_to remove_linked_image_event_path(photo_id: image.id), data: {confirm: "remove linked image?"} do %>
            <%= fa_icon "times-circle", class: "pull-right" %>
          <% end %>
          <%= link_to image_path(image) do %>
            <%= image_tag image.image.thumb.url %>
          <% end %>
        </div>
      <% end %>
    </div>
  <% end %>
</div>