config/routes.rb
Rails.application.routes.draw do

  root to: "people#index"

  post :add_note, to: "application#add_note"

  devise_for :users

  resources :users, only: :index
  get 'unauthorized', to:  'users#unauthorized', as: :unauthorized

  resources :groups

  resources :images do
    member do
      get 'full_size', to: 'images#full_size'
      get 'remove_linked_event', to: 'images#remove_linked_event'
      get 'remove_linked_person', to: 'images#remove_linked_person'
      get 'remove_linked_group', to: 'images#remove_linked_group'
    end
  end

  resources :people do
    member do
      get 'remove_linked_image', to: 'people#remove_linked_image'
      get 'remove_linked_group', to: 'people#remove_linked_group'
      get 'remove_linked_event', to: 'people#remove_linked_event'
    end
    collection do
      get 'search', to: "people#search"
    end
  end

  resources :events do
    member do
      get 'remove_linked_image', to: 'events#remove_linked_image'
      get 'remove_linked_group', to: 'events#remove_linked_group'
      get 'remove_linked_event', to: 'events#remove_linked_event'
      get 'remove_linked_person', to: 'events#remove_linked_person'
    end
  end


# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/models/image.rb
class Image < ApplicationRecord

  mount_uploader :image, ImageUploader

  has_many :person_images
  has_many :people, through: :person_images
  has_one :event_image
  has_one :event, through: :event_image
  has_many :group_images
  has_many :groups, through: :group_images
  has_many :note_images
  has_many :notes, through: :note_images

end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :set_image, only: [:show, :full_size, :edit, :update, :destroy]

  # GET /images
  # GET /images.json
  def index
    @images = Image.all.order(created_at: :asc).page(params[:page])
  end

  # GET /images/1
  # GET /images/1.json
  def show
  end

  def full_size
  end

  # GET /images/new
  def new
    @image = Image.new
    @people_for_select = Person.all.order(last_name: :asc, first_name: :asc).map{ |person| [person.full_name, person.id] }
    @events_for_select = Event.all.order(name: :asc).map{ |event| [event.name, event.id] }
    @groups_for_select = Group.all.order(name: :asc).map{ |group| [group.name, group.id] }
  end

  # GET /images/1/edit
  def edit
    @people_for_select = Person.all.order(last_name: :asc, first_name: :asc).map{ |person| [person.full_name, person.id] }
    @events_for_select = Event.all.order(name: :asc).map{ |event| [event.name, event.id] }
    @groups_for_select = Group.all.order(name: :asc).map{ |group| [group.name, group.id] }
  end

  # POST /images
  # POST /images.json
  def create
    @image = Image.new(image_params)

    respond_to do |format|
      if @image.save
        process_linking_params
        format.html { redirect_to @image, notice: 'Image was successfully created.' }
        format.json { render :show, status: :created, location: @image }
      else
        format.html { render :new }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /images/1
  # PATCH/PUT /images/1.json
  def update
    respond_to do |format|
      if @image.update(image_params)
        process_linking_params

        format.html { redirect_to @image, notice: 'Image was successfully updated.' }
        format.json { render :show, status: :ok, location: @image }
      else
        format.html { render :edit }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /images/1
  # DELETE /images/1.json
  def destroy
    @image.destroy
    respond_to do |format|
      format.html { redirect_to images_url, notice: 'Image was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def remove_linked_person
      @image = Image.find(params[:id])
      person = Person.find(params[:person_id])
      if @image.people.delete(person)
        redirect_to @image, notice: "Linked person successfully removed"
      else
        redirect_to @image, notice: "Could not remove linked person"
      end
  end

  def remove_linked_group
    @image = Image.find(params[:id])
    group = Group.find(params[:group_id])
    if @image.groups.delete(group)
      redirect_to @image, notice: "Linked group successfully removed"
    else
      redirect_to @image, notice: "Could not remove linked group"
    end
  end

  def remove_linked_event
    @image = Image.find(params[:id])
    if @image.event_image.delete
      redirect_to @image, notice: "Linked event successfully removed"
    else
      redirect_to @image, notice: "Could not remove linked event"
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_image
      @image = Image.find(params[:id])
    end

    def process_linking_params
        if !params[:image][:link_event].empty?
          @image.event = Event.find(params[:image][:link_event])
        end
        if !params[:image][:link_person].empty?
          params[:image][:link_person].each do |imp|
            unless imp.blank?
              person = Person.find(imp)
              @image.people << person unless @image.people.include?(person)
              unless @image.event.nil?
                @image.event.people << person unless @image.event.people.include?(person)
              end
            end
          end
        end

        if !params[:image][:link_group].empty?
          params[:image][:link_group].each do |gp|
            @image.groups << Group.find(gp) unless gp.blank?
          end
        end
    end


    # Never trust parameters from the scary internet, only allow the white list through.
    def image_params
      params.require(:image).permit(:description, :image, :location)
    end
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/images/_form.html.erb
<%= form_with(model: image, local: true) do |form| %>
  <% if image.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(image.errors.count, "error") %> prohibited this image from being saved:</h2>

      <ul>
        <% image.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="twelve columns">
      <%= form.label :image %>
      <%= form.file_field :image %>
    </div>
  </div>

  <div class="row">
    <div class="twelve columns">
      <%= form.label :description %>
      <%= form.text_area :description, class: "u-full-width"%>
    </div>
  </div>

  <div class="row">
    <div class="twelve columns">
      <%= form.label :location %>
      <%= form.text_field :location, class: "u-full-width"%>
    </div>
  </div>

  <div class="row">
    <div class="twelve columns">
      <%= form.label :link_person %>
      <%= form.select :link_person, @people_for_select, {include_blank: "add a person to this photo (ctrl-click to add multiple)"},{ multiple: true, class: "u-full-width multiple-select" } %>
    </div>
  </div>

  <div class="row">
    <div class="twelve columns">
      <%= form.label :link_event %>
      <%= form.select :link_event, @events_for_select, {include_blank: "add an event to this photo"}, class: "u-full-width" %>
    </div>
  </div>

  <div class="row">
    <div class="twelve columns">
      <%= form.label :link_group %>
      <%= form.select :link_group, @groups_for_select, {include_blank: "add a group to this photo (ctrl-click to add multiple)"}, {multiple: true, class: "u-full-width multiple-select"} %>
    </div>
  </div>
  
  <div class="row">
      <%= form.submit class: "button button-primary" %>
  </div> 
<% end %>

app/views/images/edit.html.erb
<h1>Editing Image</h1>


<%= form_with(model: @image, local: true) do |form| %>
  <% if @image.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@image.errors.count, "error") %> prohibited this image from being saved:</h2>

      <ul>
        <% @image.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

 <div class="row">
    <div class="twelve columns">
      <%= form.label :description %>
      <%= form.text_area :description, class: "u-full-width"%>
    </div>
  </div>

 <div class="row">
    <div class="twelve columns">
      <%= form.label :location %>
      <%= form.text_field :location, class: "u-full-width"%>
    </div>
  </div>

  <% if @image.people.any? %>
    <div>
      <h4>People in this photo</h4>
        <% @image.people.each do |person| %>
          <ul>
            <li><%= person.full_name %></li>
          </ul>
        <% end %>
    </div>
  <% end %>

 <div class="row">
    <div class="twelve columns">
      <%= form.label :link_person %>
      <%= form.select :link_person, @people_for_select, {include_blank: "add a person to this photo (ctrl-click to add multiple)"},{ multiple: true, class: "u-full-width multiple-select" } %>
    </div>
  </div>

  <% if !@image.event.blank? %>
    <div class="twelve columns">
      Event: <%= @image.event.name %>
    </div>
  <% end %>

 <div class="row">
    <div class="twelve columns">
      <%= form.label :link_event %>
      <%= form.select :link_event, @events_for_select, {include_blank: "add an event to this photo"}, class: "u-full-width" %>
    </div>
  </div>

  <% if @image.groups.any? %>
    <div>
      <h4>Groups in this photo</h4>
        <% @image.groups.each do |group| %>
          <ul>
            <li><%= group.name %></li>
          </ul>
        <% end %>
    </div>
  <% end %>

  <div class="row">
    <div class="twelve columns">
      <%= form.label :link_group %>
      <%= form.select :link_group, @groups_for_select, {include_blank: "add a group to this photo (ctrl-click to add multiple)"}, {multiple: true, class: "u-full-width multiple-select"} %>
    </div>
  </div>
  
  <div class="row">
      <%= form.submit class: "button button-primary" %>
  </div> 

<% end %>


<%= link_to 'Show', @image %> |
<%= link_to 'Back', images_path %>
<div>
  <%= image_tag @image.image.url %>
</div>

app/views/images/full_size.html.erb
<p>
  <strong>Description:</strong>
  <%= @image.description %>
</p>
<% if @image.event %>
  
  <h4>Event:</h4>
  <div>
    <%= link_to "#{@image.event.name}, #{@image.event.date}", @image.event %>
    <%= link_to remove_linked_event_image_path(event_id: @image.event.id), data: {confirm: "remove linked event?"} do %>
      <%= fa_icon "times-circle" %>
    <% end %>
  </div>
<% end %>

  <h4>Location:<%= @image.location %></h4>
<div>
  <h4>People in image</h4>
  <ul>
    <% @image.people.each do |person| %>
      <li>
        <%= link_to person.full_name, person %>
        <%= link_to remove_linked_person_image_path(person_id: person.id), data: {confirm: "remove linked person?"} do %>
          <%= fa_icon "times-circle" %>
        <% end %>
      </li>
    <% end %>
  </ul>
</div>

<div>
  <h4>Groups in Image</h4>
  <ul>
    <% @image.groups.each do |group| %>
      <li>
        <%= link_to group.name, group %>
        <%= link_to remove_linked_group_image_path(group_id: group.id), data: {confirm: "remove linked group?"} do %>
          <%= fa_icon "times-circle" %>
        <% end %>
      </li>
    <% end %>
  </ul>

</div>
<div>
  <% if @image.notes.any? %>
    <h4>Notes</h4>
    <% @image.notes.each do |note| %>
      <div><%= note.content %></div>
      <div><%= "Added #{note.created_at}" %></div>
    <% end %>
  <% end %>
</div>

<div class="note-form row">
  <%= render partial: "layouts/note_form", locals: { item_type: :image, item_id: @image.id } %>
</div>

<%= link_to 'Edit', edit_image_path(@image) %>
<div>
  <%= image_tag @image.image.url %>
</div>

app/views/images/index.html.erb
<h1>Images</h1>
<%= link_to 'New Image', new_image_path %>
<%= paginate @images %>
<table>
  <thead>
    <tr>
      <th>Description</th>
      <th>Image</th>
      <th>Actions</th>
    </tr>
  </thead>

  <tbody>

    <% @images.each do |image| %>
      <tr>
        <td><%= image.description %></td>

        <td><%= link_to image do %>
              <%= image_tag image.image.thumb.url %>
            <% end %>
        </td>
        <td><%= link_to 'Edit', edit_image_path(image) %> | <%= link_to 'Destroy', image, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/images/new.html.erb
<h1>New Image</h1>

<%= render 'form', image: @image %>

<%= link_to 'Back', images_path %>

app/views/images/show.html.erb
<p>
  <strong>Description:</strong>
  <%= @image.description %>
</p>
<% if @image.event %>
  
  <h4>Event:</h4>
  <div>
    <%= link_to "#{@image.event.name}, #{@image.event.date}", @image.event %>
    <%= link_to remove_linked_event_image_path(event_id: @image.event.id), data: {confirm: "remove linked event?"} do %>
      <%= fa_icon "times-circle" %>
    <% end %>
  </div>
<% end %>

  <h4>Location:<%= @image.location %></h4>
<div>
  <h4>People in image</h4>
  <ul>
    <% @image.people.each do |person| %>
      <li>
        <%= link_to person.full_name, person %>
        <%= link_to remove_linked_person_image_path(person_id: person.id), data: {confirm: "remove linked person?"} do %>
          <%= fa_icon "times-circle" %>
        <% end %>
      </li>
    <% end %>
  </ul>
</div>

<div>
  <h4>Groups in Image</h4>
  <ul>
    <% @image.groups.each do |group| %>
      <li>
        <%= link_to group.name, group %>
        <%= link_to remove_linked_group_image_path(group_id: group.id), data: {confirm: "remove linked group?"} do %>
          <%= fa_icon "times-circle" %>
        <% end %>
      </li>
    <% end %>
  </ul>

</div>
<div>
  <% if @image.notes.any? %>
    <h4>Notes</h4>
    <% @image.notes.each do |note| %>
      <div><%= note.content %></div>
      <div><%= "Added #{note.created_at}" %></div>
    <% end %>
  <% end %>
</div>

<div class="note-form row">
  <%= render partial: "layouts/note_form", locals: { item_type: :image, item_id: @image.id } %>
</div>

<%= link_to 'Edit', edit_image_path(@image) %><span class="pull-right"><%= link_to "Full Size", full_size_image_path(@image) %></span>
<div>
  <%= image_tag @image.image.medium.url %>
</div>