config/routes.rb
Rails.application.routes.draw do

  root to: "people#index"

  post :add_note, to: "application#add_note"

  devise_for :users

  resources :users, only: :index
  get 'unauthorized', to:  'users#unauthorized', as: :unauthorized

  resources :groups

  resources :images do
    member do
      get 'full_size', to: 'images#full_size'
      get 'remove_linked_event', to: 'images#remove_linked_event'
      get 'remove_linked_person', to: 'images#remove_linked_person'
      get 'remove_linked_group', to: 'images#remove_linked_group'
    end
  end

  resources :people do
    member do
      get 'remove_linked_image', to: 'people#remove_linked_image'
      get 'remove_linked_group', to: 'people#remove_linked_group'
      get 'remove_linked_event', to: 'people#remove_linked_event'
    end
    collection do
      get 'search', to: "people#search"
    end
  end

  resources :events do
    member do
      get 'remove_linked_image', to: 'events#remove_linked_image'
      get 'remove_linked_group', to: 'events#remove_linked_group'
      get 'remove_linked_event', to: 'events#remove_linked_event'
      get 'remove_linked_person', to: 'events#remove_linked_person'
    end
  end


# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/models/event.rb
class Event < ApplicationRecord

  has_many :event_videos
  has_many :videos, through: :event_videos
  has_many :person_events
  has_many :people, through: :person_events
  has_many :event_images
  has_many :images, through: :event_images
  has_many :note_events
  has_many :notes, through: :note_events

  accepts_nested_attributes_for :images
end

app/models/event_image.rb
class EventImage < ApplicationRecord

  belongs_to :event
  belongs_to :image

end

app/models/event_video.rb
class EventVideo < ApplicationRecord

  belongs_to :event
  belongs_to :video

end

app/models/group.rb
class Group < ApplicationRecord

  has_many :group_people
  has_many :people, through: :group_people
  has_many :group_images
  has_many :images, through: :group_images
  has_many :note_groups
  has_many :notes, through: :note_groups
end

app/models/group_image.rb
class GroupImage < ApplicationRecord

  belongs_to :group
  belongs_to :image

end

app/models/group_person.rb
class GroupPerson < ApplicationRecord

  belongs_to :group
  belongs_to :person
end

app/models/image.rb
class Image < ApplicationRecord

  mount_uploader :image, ImageUploader

  has_many :person_images
  has_many :people, through: :person_images
  has_one :event_image
  has_one :event, through: :event_image
  has_many :group_images
  has_many :groups, through: :group_images
  has_many :note_images
  has_many :notes, through: :note_images

end

app/models/note.rb
class Note < ApplicationRecord

  belongs_to :note_event, optional: true
  belongs_to :note_group, optional: true
  belongs_to :note_image, optional: true
  belongs_to :note_person, optional: true

end

app/models/note_event.rb
class NoteEvent < ApplicationRecord

  belongs_to :event
  belongs_to :note

end

app/models/note_group.rb
class NoteGroup < ApplicationRecord

  belongs_to :note
  belongs_to :group

end

app/models/note_image.rb
class NoteImage < ApplicationRecord

  belongs_to :note
  belongs_to :image

end

app/models/note_person.rb
class NotePerson < ApplicationRecord

  belongs_to :note
  belongs_to :person

end

app/models/person.rb
class Person < ApplicationRecord

  has_many :person_events
  has_many :events, through: :person_events
  has_many :person_images
  has_many :images, through: :person_images
  has_many :group_people
  has_many :groups, through: :group_people
  has_many :note_people
  has_many :notes, through: :note_people

  def full_name
    first_name.to_s + " " + last_name.to_s
  end

end

app/models/person_event.rb
class PersonEvent < ApplicationRecord

  belongs_to :person
  belongs_to :event

end

app/models/person_image.rb
class PersonImage < ApplicationRecord

  belongs_to :person
  belongs_to :image

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :rememberable, :recoverable, :trackable, :validatable, :timeoutable #add :invitable :lockable,
end

app/models/video.rb
class Video< ApplicationRecord

  mount_uploader :video, VideoUploader

  has_one :event_image
  has_one :event, through: :event_image

end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/layouts/_note_form.html.erb
<%= form_with(url: "/add_note", method: :post) do  %>
  
  <%= label_tag "Add a note" %>
  <%= text_area_tag :content, nil, {class: "u-full-width"} %>
  <%= hidden_field_tag :item_type, item_type %>
  <%= hidden_field_tag :item_id, item_id %>
  <%= submit_tag "Create" %>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PhotoSharing</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
  <div class="container">
  <% if user_signed_in? && current_user.authorized %>
    <div class="navbar">
      <%= link_to "People", people_path %> | 
      <%= link_to "Images", images_path %> | 
      <%= link_to "Events", events_path %> |
      <%= link_to "Groups", groups_path %>
      <span class="pull-right">
        <%= link_to "log out", destroy_user_session_path, method: :delete %>
      </span>
    </div>
  <% end %>
    <p id="notice"><%= notice %></p>
    <%= yield %>
  </div>
  </body>
</html>